### ISSUE TITLE
Import error when using React along with Typescript

### ISSUE THREAD

**Issue by f32by** [pixijs/pixi-layers#47]
Hello,

I installed pixi.js and pixi-layers by
```shell
yarn add pixi.js pixi-layers
```

and then I tried following code:
```typescript
import 'pixi-layers'
import * as PIXI from 'pixi.js'

const test = new PIXI.display.Group(100, false)
```

but it throws an error:
```
./src/index.tsx
Attempted import error: 'display' is not exported from 'pixi.js' (imported as 'PIXI').
```

**Comment by stefan-reloyalty** [comment]
Have you tried changing the order of imports? Like:

import * as PIXI from 'pixi.js'
import 'pixi-layers'

const test = new PIXI.display.Group(100, false)

**Comment by hellotanuky** [comment]
still the same error :(

**Comment by Mathieu-C** [comment]
@hellotanuky Have you found a way around this issue? I'm facing the same problem, thinking of compiling all Pixi-related code independently from React and bundling everything together with webpack but curious to hear from you.

**Comment by noih** [comment]
try to use `window.PIXI.display` instead of `PIXI.display`

```javascript
import * as PIXI from 'pixi.js';

window.PIXI = PIXI;
require('pixi-layers');

const test = new window.PIXI.display.Group(100, false);
```
