### ISSUE TITLE
mask.containsPoint is not a function when importing 'pixi-layers'

### ISSUE THREAD

**Issue by Ilko89BG** [pixijs/pixi-layers#54]
Hello there,
   Without any code or any implementation - just when I import the package I get this error when hovering over a mask. 
![Selection_006](https://user-images.githubusercontent.com/20794896/77234240-666ea000-6bb5-11ea-8bfd-b4734c03a0f6.png)
![Selection_005](https://user-images.githubusercontent.com/20794896/77234206-36270180-6bb5-11ea-9827-2c7964d26f61.png)

 Not going to use it for now, but just wanted to point out this issue.

Regards,
   Iliya Iliev

**Comment by ivanpopelyshev** [comment]
oh !@$# i forgot to modify this plugin after MaskData was introduced.

See this function? https://github.com/pixijs/pixi-layers/blob/master/src/LayersTreeSearch.ts#L40

That's how it is in pixi: https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.js#L87

I suggest to patch it and see if it works :

```js
PIXI.display.LayersTreeSearch.prototype.recursiveFindHit = function(params) {
//...
// same as in pixi-layers bug with fix
}
```

I'll make new build tomorrow :) Is that ok?

**Comment by Ilko89BG** [comment]
> oh !@$# i forgot to modify this plugin after MaskData was introduced.
> 
> See this function? https://github.com/pixijs/pixi-layers/blob/master/src/LayersTreeSearch.ts#L40
> 
> That's how it is in pixi: https://github.com/pixijs/pixi.js/blob/dev/packages/interaction/src/TreeSearch.js#L87
> 
> I suggest to patch it and see if it works :
> 
> ```js
> PIXI.display.LayersTreeSearch.prototype.recursiveFindHit = function(params) {
> //...
> // same as in pixi-layers bug with fix
> }
> ```
> 
> I'll make new build tomorrow :) Is that ok?

Perfectly fine, thanks again, Ivan. You are quite prompt! :)

**Comment by Ilko89BG** [comment]
Sorry if I am being pushy - but any updates on this? Or at least can you give me some pointers as to how to handle the issues I mentioned in the previous post.

**Comment by ivanpopelyshev** [comment]
Oh, i forgot it. 

```
however I find difficulties understanding how to properly find interactiveEvent.target - maybe I am just not understanding something - haven't read thoroughly the library - but will do that for sure!
```

I dont understand what are you talking about. The goal is just to copy the method like it is in pixi-layers and fix particular line 

```
if (!(displayObject._mask.containsPoint && displayObject._mask.containsPoint(point)))**
```

you dont have to port other changes.

**Comment by Ilko89BG** [comment]
> Oh, i forgot it.
> 
> ```
> however I find difficulties understanding how to properly find interactiveEvent.target - maybe I am just not understanding something - haven't read thoroughly the library - but will do that for sure!
> ```
> 
> I dont understand what are you talking about. The goal is just to copy the method like it is in pixi-layers and fix particular line
> 
> ```
> if (!(displayObject._mask.containsPoint && displayObject._mask.containsPoint(point)))**
> ```
> 
> you dont have to port other changes.

Ok, got it! - Will try it out, thanks.

**Comment by Ilko89BG** [comment]
`
// it has a mask! Then lets hit test that before continuing..
  const mask: Graphics = (displayObject as any)._mask;
  if (hitTestOrder < Infinity && mask) {
    if (!(mask.containsPoint && mask.containsPoint(point))) {
      outOfMask = true;
    }
  }
`

Yes, this doesn't throw the error - thanks again, Ivan!
