### ISSUE TITLE
ParticleContainer renders twice

### ISSUE THREAD

**Issue by SnowyCoder** [pixijs/pixi-layers#60]
Thanks for everything, I've been using your projects and they'e amazing!

I've noticed that when profiling my application with SpectorJS the ParticleContainers render twice, first in their original containers, then in their parentLayers (when they have both).
I think that this is because the ContainerMixin replaces the "render" function but the overridden "render" function from the ParticleContainer takes precedence so it will not skip the first render.
This means that the bug is present for every Container class that overrides the "render" function.

### Workaround
Wrap the ParticleContainer in a Container and place that in the layer, the outer layer will then skip the rendering before recurring in the children.

### Possible Solution
I can't think of any easy solutions

### Environment

- **`pixi.js` version**: 5.3.3
- **`pixi-layers` version**: 0.3.1
- **Browser & Version**: Firefox 79.0
- **OS & Version**: 5.4.57-1-MANJARO + KDE Plasma 5.12.4

**Comment by ivanpopelyshev** [comment]
oh, i didnt test it with ParticleContainer properly. thanks!

**Comment by SnowyCoder** [comment]
If you want a hand I could help with this, I explored quite a bit of the codebase (I need a lot of pixi details for a project of mine).
Problem is I can't think of a solution that will solve the general problem without changing too much code (can we do this with no changes in the core package?).

**Comment by ivanpopelyshev** [comment]
I forgot about this issue :( Sorry, im too busy this week, and maybe next, i just dont know if i can check that thing. If you find what to change here, just make a PR.

**Comment by ivanpopelyshev** [comment]
Can you just override ParticleContainer render in prototype ?

**Comment by SnowyCoder** [comment]
It would work in this case but It would still be broken in other Container subclasses that override the 'render' function (there don't seem to be any in pixi core but custom RenderObjects can override it and it seems to be a "best practice").
