### ISSUE TITLE
Types not compatible with Pixijs 6.0..0

### ISSUE THREAD

**Issue by AllNamesRTaken** [pixijs/pixi-layers#65]
Upgraded from Pixi 5.3.8 to 6.0.0 and it the type fail to extend the declarations of pixi.

Likely due to the fact that pixi.js 5.3.8 had ambient declarations while 6.0.0 seem to export them.

**Comment by ivanpopelyshev** [comment]
Its possible to extend global interfaces. What exactly do you want to extend?

**Comment by saqirmdevx** [comment]
> Its possible to extend global interfaces. What exactly do you want to extend?

Hey, it is not working for me aswell. I am actually migrating to V6 pixi, everything works fine except pixi-layers

When i am extending my scene for example: export default abstract class Scene extends Stage

Stage is not extending from PIXI's container thus has no access to its properties. 
i cant even add scene into app.stage because it is not instance of Container

**Comment by ivanpopelyshev** [comment]
Yes, I still didnt port it to v6. Too much work right now :(

**Comment by ivanpopelyshev** [comment]
Actually, you can help me with that - certain team members keep telling me that my plugins are not used by people and are not worth it for pixijs community. If you post that issue about pixi-tilemap in main pixijs with description of how you use it - that'll be appreciated :)

**Comment by saqirmdevx** [comment]
> Actually, you can help me with that - certain team members keep telling me that my plugins are not used by people and are not worth it for pixijs community. If you post that issue about pixi-tilemap in main pixijs with description of how you use it - that'll be appreciated :)

pixi-tilemap works well for me (@pixi-tilemap v3.2)
i am using kinda custom implementation and usage of TILED editor.

import { CompositeRectTileLayer } from '@pixi/tilemap'; // I am using only this method from pixi tilemap
which is created for each layer. I can provide my code but i am not sure if it is correct way to use it.

**Comment by saqirmdevx** [comment]
@ivanpopelyshev 
    "pixi-filters": "^4.1.0",
    "pixi-layers": "^0.3.1",
    "pixi-particles": "^4.3.0",
    "pixi-viewport": "^4.31.0",

    Modules that i am currently using, they are very useful. Also i will use lights in future for my game and many other modules.

- Saying that those modules are useless is kinda weird, all modules have their usecase.

**Comment by saqirmdevx** [comment]
> Actually, you can help me with that - certain team members keep telling me that my plugins are not used by people and are not worth it for pixijs community. If you post that issue about pixi-tilemap in main pixijs with description of how you use it - that'll be appreciated :)

i think i missunderstood question :-P

**Comment by ivanpopelyshev** [comment]
There was a post with plugin list. Return it back please :) I'll move pixi-layers to v6 soon, dont worry

**Comment by saqirmdevx** [comment]
> There was a post with plugin list. Return it back please :) I'll move pixi-layers to v6 soon, dont worry

Oh i am sorry 
Plugins that i am using: 
    "@pixi/tilemap": "^3.2.0",
    "pixi-filters": "^4.1.0",
    "pixi-layers": "^0.3.1",
    "pixi-particles": "^4.3.0",
    "pixi-viewport": "^4.31.0",
    
    I used those plugins in almost all projects i have ever done in PIXI

**Comment by AllNamesRTaken** [comment]
Just to chime in,
pixi-layers is absolutely essential to me and thanks for maintaining it
Ivan.

//J

Den tors 13 maj 2021 kl 17:57 skrev Naščák Martin ***@***.***

**Comment by wpitallo** [comment]
Pixi layer is awesome!!! Should be incorporated into Pixi.js if you ask me.🥳🥳🥳🥳🥳

**Comment by saqirmdevx** [comment]
All those plugins are awesome and save lot of time for people which are using PIXI Js. Pixi-layer should be implemented in PIXIJs by default aswell as Viewport (or any camera system) ( I know it is easy to make your own).
Also i found very useful pixi-tilemap plugin almost for all games which are using tile-based world

**Comment by yordan-kanchelov** [comment]
> Actually, you can help me with that - certain team members keep telling me that my plugins are not used by people and are not worth it for pixijs community. If you post that issue about pixi-tilemap in main pixijs with description of how you use it - that'll be appreciated :)

I know many people who won't migrate to v6 only because of the missing pixi-layers support :) .

**Comment by ivanpopelyshev** [comment]
https://www.html5gamedevs.com/topic/47356-using-pixi-with-vitetypescript/

someone made custom typings

**Comment by saqirmdevx** [comment]
> https://www.html5gamedevs.com/topic/47356-using-pixi-with-vitetypescript/
> 
> someone made custom typings

It looks good, could it be checked and added into main repo?

**Comment by ivanpopelyshev** [comment]
My friends, I just published `@pixi/layers` , version `1.0.0`. Thank you for all the kind words, now its time to test it!

Functionality is the same, it requires a bit of migration regarding CanvasRenderer and Particles (see README).

**Comment by ivanpopelyshev** [comment]
And now i published `1.0.1` because of my derp in the only line of code I actually changed

**Comment by ivanpopelyshev** [comment]
Forgot globals :( now its `1.0.2`
